FROM adminer:latest

# FROM debian:bullseye


# RUN apt -y update 

# COPY ./tools/script.sh /

# RUN apt install wget -y && apt install php php-mysql  -y

# RUN chmod 777 script.sh

# CMD ["/script.sh"]